langventure/urls.py
from django.contrib import admin
from django.urls import path, include
from .settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('gapfiller.urls')),
    path("", include('story.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

story/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("story/<int:id>", views.story, name="story"),
    path("story_scene/<int:id>/<int:scene_id>", views.story_scene, name="story_scene"),
    path("publish/<int:story_id>", views.publish_story, name="publish"),
    path("create_story/", views.create_story, name="create_story"),
    path("actor/<int:scene_id>", views.actor, name="actor"),
    path("collectible/<int:scene_id>", views.collectible, name="collectible"),
    path("edit_actor/<int:actor_id>", views.edit_actor, name="edit_actor"),
    path("get_actor_info/<int:actor_id>", views.get_character_info, name="get_actor"),
    path("create_character/<int:scene_id>", views.create_character, name="create_character"),
    path("create_scene/<int:story_id>", views.create_new_scene, name="create_scene"),
    path("update_character/<int:char_id>", views.update_character, name="update_character"),
    path("dialog", views.dialog, name="dialog"),
    path("background/<int:scene_id>", views.set_background, name="background"),
    path("set_character_pos_scale/<int:char_id>", views.set_character_pos_scale, name="set_character_pos_scale"),
    path("set_collectible_pos_scale/<int:char_id>", views.set_collectible_pos_scale, name="set_collectible_pos_scale"),
    path("get_dialog/<int:char_id>", views.get_dialog, name="get_dialog"),
    path("set_scene_description/<int:scene_id>", views.set_scene_description, name="set_scene_description"),
    path("set_scene_name/<int:scene_id>", views.set_scene_name, name="set_scene_name"),
    path("set_story_name/<int:story_id>", views.set_story_name, name="set_story_name"),
    path("set_story_description/<int:story_id>", views.set_story_description, name="set_story_description"),
    path("update_story/<int:story_id>", views.update_story, name="update_story"),
    path("update_story_scene/<int:story_id>/<int:scene_id>", views.update_story_scene, name="update_story_scene"),
    path("update_menu", views.update_menu, name="update_menu"),
    path("delete_scene/<int:scene_id>", views.delete_scene, name="delete_scene"),
    path("update_user_knowledge", views.update_user_knowledge, name="update_user_knowledge"),
    path("update_scene_knowledge/<int:scene_id>", views.update_scene_knowledge, name="update_scene_knowledge"),
    path("get_scene_knowledge/<int:scene_id>", views.get_scene_knowledge, name="get_scene_knowledge"),
    path("get_active_scenes/<int:scene_id>", views.get_active_scenes, name="get_active_scenes"),
    path("get_dialog_audio/<int:dialog_id>", views.get_dialog_audio, name="get_dialog_audio"),
    path("get_option_audio/<int:dialog_id>", views.get_option_audio, name="get_option_audio")
]

story/models.py
from django.db import models
from gapfiller.models import User, Language
from gtts import gTTS
import io
from django.core.files.base import ContentFile
import tempfile
import os


class Story(models.Model):
    name = models.TextField()
    description = models.TextField(default="")
    org_lang = models.ForeignKey(Language, on_delete=models.CASCADE, blank=True, default=None, null=True, related_name="org_lang")
    dest_lang = models.ForeignKey(Language, on_delete=models.CASCADE, blank=True, default=None, null=True, related_name="dest_lang")
    created = models.DateTimeField(null=True, blank=True, default=None)
    finished = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="storys", default="")


class Scene(models.Model):
    story = models.ForeignKey(Story, blank=True, default=None, on_delete=models.CASCADE, related_name="scenes")
    name = models.TextField()
    background = models.ImageField(blank=True, default=None, upload_to="images")
    description = models.TextField(default="")
    users = models.ManyToManyField(User, blank=True, related_name="scences")


class Actor(models.Model):
    scene = models.ForeignKey(Scene, blank=True, default=None, on_delete=models.CASCADE, related_name="actors")
    name = models.TextField()
    image = models.ImageField(blank=True, default=None, upload_to="images")
    scale = models.TextField(default="scale(1)")
    top = models.TextField(default="10px")
    left = models.TextField(default="50px")


class Dialog(models.Model):
    name = models.TextField()
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE, related_name="dialogs")
    bubble = models.TextField()
    audio = models.FileField(
        upload_to='podcasts/', null=True, blank=True)
    translation = models.TextField(default="")

    def save_audio(self):
        #tts = gTTS(self.bubble, lang='de')  # Change lang as needed
        tts = gTTS(self.bubble, lang='it')  # Change lang as needed
        audio_buffer = io.BytesIO()

        # Create a temporary file
        temp_file_path = f'tmp_dialog_audio_{self.pk}.mp3'
        tts.save(temp_file_path)

        # Read the temporary file into the audio_buffer
        with open(temp_file_path, 'rb') as temp_file:
            audio_buffer.write(temp_file.read())

        audio_buffer.seek(0)
        audio_file_name = f'dialog_audio_{self.pk}.mp3'
        self.audio.save(audio_file_name, ContentFile(audio_buffer.read()))

        # Remove the temporary file
        os.remove(temp_file_path)


class Knowledge(models.Model):
    item = models.CharField(max_length=50)
    story = models.ForeignKey(Story, on_delete=models.CASCADE, blank=True, null=True, related_name="knowledge_items")
    users = models.ManyToManyField(User, blank=True, related_name="knowledge_items")
    required_scenes = models.ManyToManyField(Scene, blank=True, related_name="requires")
    deactivated_scenes = models.ManyToManyField(Scene, blank=True, related_name="deactivates")


class Collectible(models.Model):
    scene = models.ForeignKey(Scene, blank=True, default=None, on_delete=models.CASCADE, related_name="collectibles")
    name = models.CharField(max_length=50)
    knowledge_item = models.ForeignKey(Knowledge, on_delete=models.CASCADE, related_name="collectible")
    image = models.ImageField(blank=True, default=None, upload_to="images")
    scale = models.TextField(default="scale(1)")
    top = models.TextField(default="10px")
    left = models.TextField(default="50px")

    def __str__(self):
        return self.name


class Option(models.Model):
    origin = models.ForeignKey(Dialog, on_delete=models.CASCADE, related_name="options")
    target = models.ForeignKey(Dialog, on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField()
    translation = models.TextField(default="")
    acquired = models.ForeignKey(
        Knowledge,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="acquire_options"
    )
    required_k_items = models.ManyToManyField(
        Knowledge,
        blank=True,
        related_name="require_options"
    )
    disabled_k_items = models.ManyToManyField(
        Knowledge,
        blank=True,
        related_name="disabled_options"
    )
    audio = models.FileField(
        upload_to='podcasts/', null=True, blank=True)

    def save_audio(self):
        #tts = gTTS(self.text, lang='de')  # Change lang as needed
        tts = gTTS(self.text, lang='it')  # Change lang as needed
        audio_buffer = io.BytesIO()

        # Create a temporary file
        temp_file_path = f'tmp_option_audio_{self.pk}.mp3'
        tts.save(temp_file_path)

        # Read the temporary file into the audio_buffer
        with open(temp_file_path, 'rb') as temp_file:
            audio_buffer.write(temp_file.read())

        audio_buffer.seek(0)
        audio_file_name = f'dialog_option_audio_{self.pk}.mp3'
        self.audio.save(audio_file_name, ContentFile(audio_buffer.read()))

        # Remove the temporary file
        os.remove(temp_file_path)


class UserStoryConfig(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="stories")
    story = models.ForeignKey(Story, on_delete=models.CASCADE, related_name="configs")
    current_dialog = models.ForeignKey(Dialog, on_delete=models.CASCADE)


class OptionTokens(models.Model):
    option = models.ForeignKey(Option, on_delete=models.CASCADE, related_name="tokens")
    word = models.CharField(max_length=50)


class DialogTokens(models.Model):
    dialog = models.ForeignKey(Dialog, on_delete=models.CASCADE, related_name="tokens")
    word = models.CharField(max_length=50)

story/templates/story/actor.html
{% extends "gapfiller/layout.html" %}
{% load static %}
{% block body %}
    <script type="text/javascript" src="{% static 'story/actor.js' %}"></script>
    <div id="id_story" data-storyid="{{ story_id }}"></div>
    {% if scene_id %}
        <div id="id_storage" data-sceneid="{{ scene_id }}"></div>
    {% endif %}
    {% if actor_id %}
        <div id="id_actor" data-actorid="{{ actor_id }}"></div>
    {% endif %}
    <div class="actor_title">
            <h1> Create new character</h1>
    </div>
    <div class="create_section">

        {% if message %}
            <div class="create_warning"> <p>{{ message }}</p> </div>
        {% endif %}

        <div>
            {% csrf_token %}
            <div class="left_actor_box">
                <div class="inner_box">
                    <div>
                        <h4 style="margin:0px;margin-left:5px;margin-bottom:5px;">Knowlegde items</h4>
                    </div>
                    <div style="display: flex; margin:5px; border-radius:5px; color:black">
                        <div id="knowledge_items" style="display:none">
                            {% for item in story.knowledge_items.all %}
                                {{ item.item }}
                            {% endfor %}
                        </div>
                        <div id="knowledge" style="background-color: white; height: 80px; flex: 1; border-radius: 5px; padding: 5px;">
                        </div>
                        <div style="display: flex; flex-direction: column; width: 200px;">
                            <input id = "k-text" type="text" style="height: 40px; margin-left: 1px; border-radius: 5px;">
                            <div id = "add-k" class="btn btn-secondary" style="height: 40px; margin-left: 1px">Add knowledge-item</div>
                        </div>
                    </div>

                    <div>
                        <h4 id="current_dialog" style="margin:0px;margin-left:5px;">Current dialog: start</h4>
                    </div>
                    <div style="background:white;
                                padding:0px;
                                border-radius:5px;
                                color:black;
                                margin:5px;
                                margin-top:2px;
                                min-height:50px;"
                    >
                        <textarea id="bubble"
                              style="width:100%;
                                     margin:0px;
                                     border-radius:5px;
                                    "
                        ></textarea>
                    </div>
                    <div>
                        <h4 id="translation_title" style="margin:0px;margin-left:5px;">Translation</h4>
                    </div>
                    <div style="background:white;
                                padding:0px;
                                border-radius:5px;
                                color:black;
                                margin:5px;
                                margin-top:2px;
                                min-height:50px;"
                    >
                        <textarea id="translation"
                              style="width:100%;
                                     margin:0px;
                                     border-radius:5px;
                                    "
                        ></textarea>
                    </div>

                    <div style="background: white;
                                color:black;
                                margin:5px;
                                border-radius:5px;
                                padding:5px;"
                    >
                        <table style="width:100%;" id="options">
                        </table>
                    </div>
                    <div class="form-group" style="margin:0px;padding:5px;color:black;display:flex">
                            <input autofocus class="form-control" style="width:80%;"
                                   id="option_content"
                                   type="text"
                                   name="name"
                                   placeholder="Choose content of option"
                            >
                            <select style="width:10%;border-radius:5px;" id="selection">
                            </select>
                            <div class="btn btn-secondary" id="create_option" style="font-size:13px;width:10%;margin-top:0px;">
                                create option
                            </div>
                    </div>
                    <div style="margin:5px;">
                        <a class="btn btn-secondary"
                           style="width:100%; margin-bottom: 5px;"
                           type="submit"
                           id="dialog"
                           href="{% url 'dialog'  %}"
                           value="Create character">
                            Test dialog
                        </a>
                        {% if not actor_id %}
                            <div class="btn btn-secondary"
                                style="width:100%;"
                                type="submit"
                                id="create_char"
                                href="{% url 'update_story_scene' story_id scene_id %}"
                                value="Create character">
                                Create Character
                            </div>
                        {% endif %}
                        {% if actor_id %}
                            <div class="btn btn-secondary"
                                style="width:100%;"
                                type="submit"
                                id="update_char"
                                href="{% url 'update_story_scene' story_id scene_id %}"
                                value="Update character">
                                Update Character
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="right_actor_box">
                <div class="inner_box">
                    <div class="name_box">
                        <h4 style="margin:0px;">Name</h4>
                        <div class="form-group" style="margin:0px;">
                            {% if name %}
                            <input autofocus class="form-control"
                                   type="text"
                                   name="name"
                                   id="char_name"
                                   value="{{ name }}"
                                >
                            {% else %}
                                <input autofocus class="form-control"
                                   type="text"
                                   name="name"
                                   id="char_name"
                                   placeholder="Choose the name of the character"
                                >
                            {% endif %}
                        </div>
                    </div>
                    <div class="inner_box">
                        <h4 style="margin:0px;">Image</h4>
                        <div id="portrait">
                            {% if image %}
                                <img src="{{ image.url }}"
                                     style="width:50%;
                                            position:relative;
                                            margin-left:auto;
                                            margin-right:auto;
                                            display:block;"
                                >
                            {% endif %}
                        </div>
                        <input type="file"
                            id="avatar" name="avatar"
                           accept="image/png, image/jpeg">
                    </div>
                    <div class="dialog_box">
                        <div style=
                                "border-top-right-radius:5px;
                                border-top-left-radius:5px;
                                margin-top:5px;"
                        >
                            <h4 style="margin:0px;">Dialogs</h4>
                        </div>
                        <div class="dialog_selection" id="dialogs">
                        </div>
                        <div class="form-group add_dialog">
                            <input autofocus class="form-control"
                                   id="dialog_content"
                                   type="text"
                                   name="name"
                                   placeholder="Choose new dialog title"
                            >
                            <div    id="new_dialog"
                                    class="btn btn-secondary"
                                    style="font-size:13px;width:37%"
                            >
                                add dialog
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story/templates/story/collectible.html
{% extends "gapfiller/layout.html" %}
{% load static %}

{% block body %}

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const imageInput = document.getElementById('image');
      const imageBox = document.getElementById('image_box');

      function previewImage(input) {
        if (input.files && input.files[0]) {
          const reader = new FileReader();
          reader.onload = function (e) {
            const img = document.createElement('img');
            img.src = e.target.result;
            img.style.width = '100%';
            img.style.height = '100%';
            img.style.objectFit = 'contain';
            img.style.borderRadius = '5px';
            imageBox.innerHTML = ''; // Clear the image_box content
            imageBox.appendChild(img); // Append the img element to the image_box
          };
          reader.readAsDataURL(input.files[0]);
        }
      }

      imageInput.addEventListener('change', function() {
        previewImage(this);
      });
    });
  </script>

  <div id="id_story" data-storyid="{{ story_id }}"></div>

  {% if scene_id %}
    <div id="id_storage" data-sceneid="{{ scene_id }}"></div>
  {% endif %}

  {% if actor_id %}
    <div id="id_collectible" data-collectibleid="{{ collectible_id }}"></div>
  {% endif %}

  <div class="actor_title">
    <h1>Create new Collectible</h1>
  </div>

  <div class="create_section" style="display: flex; align-items: center; justify-content: center; height:300px">
    {% if message %}
      <div class="create_warning">
        <p>{{ message }}</p>
      </div>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div style="display: flex; flex-direction: column; justify-content: center; align-items: flex-start; margin-right: 20px;">
        <label for="name" style="color: black; font-size: 16px; margin-bottom: 10px;">Collectible Name:</label>
        <input type="text" id="name" name="name" placeholder="Enter collectible name" style="width: 300px; height: 30px; border-radius: 5px; padding: 5px; margin-bottom: 10px;">

        <label for="knowledge_item" style="color: black; font-size: 16px; margin-bottom: 10px;">Acquires Knowledge Item:</label>
        <select id="knowledge_item" name="knowledge_item" style="width: 300px; height: 30px; border-radius: 5px; padding: 5px; margin-bottom: 10px;">
          {% for item in knowledge_items %}
            <option value="{{ item.pk }}"> {{ item.item }} </option>
          {% endfor %}
        </select>

        <label for="image" style="color: black; font-size: 16px; margin-bottom: 10px;">Collectible Image:</label>
        <input type="file" id="image" name="image" accept="image/png, image/jpeg" style="margin-bottom: 10px;">
        <input type="submit" class="btn btn-secondary" value="Create Collectible" style="width:100%">
      </div>

    </form>

    <div id="image_box" style="width: 300px; height: 300px; border: 1px solid black; background-color: black;border-radius:5px"></div>
  </div>
{% endblock %}

story/templates/story/create_story.html
{% extends "gapfiller/layout.html" %}
{% load static %}
{% block body %}
    <script type="text/javascript" src="{% static 'story/create_story.js' %}"></script>
    <div class="actor_title">
            <h1> Create new Langventure</h1>
    </div>


    <div class="create_section" style="min-height:100%;">

        {% if message %}
            <div class="create_warning"> <p>{{ message }}</p> </div>
        {% endif %}

        {% for actor in current_scene.actors.all %}
                <img class="actor"
                     src="{{ actor.image.url }}"
                     data-scale="{{ actor.scale }}"
                     data-top="{{ actor.top }}"
                     data-left="{{ actor.left }}"
                     data-charid = "{{ actor.id }}"
                     style="position:absolute; margin-top:0px;">
        {% endfor %}

        {% for collectible in current_scene.collectibles.all %}
                <img class="collectible"
                     src="{{ collectible.image.url }}"
                     data-scale="{{ collectible.scale }}"
                     data-top="{{ collectible.top }}"
                     data-left="{{ collectible.left }}"
                     data-charid = "{{ collectible.id }}"
                     style="position:absolute; margin-top:0px;">
        {% endfor %}

        <div>
            {% csrf_token %}
            <div class="left_actor_box"
                 id="bg"
                 data-sceneid="{{ current_scene_id }}"
                 data-storyid="{{ story.id }}"
                 style="width:800px;background:#39395f;color:#f5eec2;">
                {% if current_scene.background %}
                    <img src="{{ current_scene.background.url }}" style="width:800px;height:600px;border-radius:5px;">
                {% else %}
                    <img style="width:800px;height:600px;border-radius:5px;background:black">
                {% endif %}
                <div style="padding:5px;">
                    <label for="story_name"> Story title </label>
                    <input type="text" id="story_name" style="width:100%;border-radius:5px;" value="{{story.name}}">
                    <input type="text" id="story_description" style="width:100%;border-radius:5px;" value="{{story.description}}">
                    <div id="publish" class="btn btn-secondary" style="width:100%;margin-top:3px;">
                        publish story
                    </div>
                </div>

            </div>
            <div class="right_actor_box" id="right_box" style="margin:0px">
                <div class="inner_box" style="padding:5px;width:49%;display:inline-block;margin:0px;">
                     <h4>Sence name</h4>
                     <input type="text"
                            id="name"
                            style="margin-top:-5px; margin-bottom:5px; border-radius:5px;width:100%"
                            value="{{ current_scene.name }}"
                     >
                    <h4>Sence description</h4>
                     <textarea
                            id="description"
                            rows="3"
                            style="margin-top:-5px; margin-bottom:5px; border-radius:5px; width:100%; rows:3;"
                     >{{current_scene.description}}</textarea>
                    <h4>background</h4>
                     <input type="file"
                            id="bgi" name="bgi"
                            accept="image/png, image/jpeg"
                     >
                    <h4>Knowledge items</h4>
                    <div>
                        <div style="background:white; color:black;padding:3px;border-radius:5px;">
                            {% for item in story.knowledge_items.all %}
                                 {{item.item}}
                            {% endfor %}
                        </div>
                        <h5>Requires</h5>
                        <div id="display_req" style="background:white; color:black;padding:3px;border-radius:5px;margin-bottom:3px">
                            None
                        </div>
                        <div class="d-flex">
                            <select id="requires" name="requires" class="form-control">
                            <option value="">None</option>
                                {% for item in story.knowledge_items.all %}
                                <option value="{{item.item}}">{{item.item}}</option>
                                {% endfor %}
                            </select>
                            <div id="add_req" class="btn btn-secondary btn-sm">add</div>
                        </div>
                        <h5>Deactivates</h5>
                        <div id="display_dea" style="background:white; color:black;padding:3px;border-radius:5px;margin-bottom:3px">
                            None
                        </div>
                        <div class="d-flex">
                            <select id="deactivates" name="deactivates" class="form-control">
                            <option value="">None</option>
                                {% for item in story.knowledge_items.all %}
                                <option value="{{item.item}}">{{item.item}}</option>
                                {% endfor %}
                            </select>
                            <div id="add_dea" class="btn btn-secondary btn-sm">add</div>
                        </div>
                    </div>
                    <h4>Select Scene</h4>
                    <div id="all_scenes" style="background:white;border-radius:5px;color:black;padding:5px;">
                        {% for scene in story.scenes.all %}
                            {% if scene.name == current_scene.name %}
                                <div style="width:100%;background:#f5eec2;border-radius:5px;">
                                    <a class="scene_selection"
                                        href="{% url 'update_story_scene' story.id scene.id %}"
                                        style="width:50%;background:#f5eec2;"
                                        data-sceneid="{{ scene.id }}"
                                    >
                                    {{scene.name}}
                                    </a>
                                </div>
                            {% else %}
                                <div>
                                    <a class="scene_selection"
                                    href="{% url 'update_story_scene' story.id scene.id %}"
                                    style="width:100%"
                                    data-sceneid="{{ scene.id }}"
                                    >
                                        {{scene.name}}
                                    </a>
                                    <img src="/media/delete.png"
                                         width="20px"
                                         class="del_scene"
                                         data-sceneid="{{ scene.id }}"
                                         style="float:right"
                                    >
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <input type="text"
                           id="scene_name"
                           placeholder="choose new scene name"
                           style="width:100%"
                    >
                    <div class="btn btn-secondary"
                         id="add_scene"
                         style="width:100%;margin-top:5px;"
                    >
                        add new scene
                    </div>
                </div>
                <div class="inner_box" style="padding:5px;width:49%;display:inline-block;vertical-align:top;margin:0px;">
                    <div>
                        <h4>To edit a character click on him</h4>
                        <div style="background:white;color:black;border-radius:5px;width=100%;padding:5px;">
                            {% for actor in current_scene.actors.all %}
                            <div>
                                {% if actor.name %}
                                    <a href="{% url 'edit_actor' actor.id %}" style="width:100%">{{ actor.name }}</a>
                                {% else %}
                                    <a href="{% url 'edit_actor' actor.id %}" style="width:100%">No Name</a>
                                {% endif %}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <a class="btn btn-secondary" style="width:100%;margin-top:5px;" href="{% url 'actor' current_scene.id %}">
                        add new character
                    </a>

                    <div style="margin-top:20px;">
                        <h4>To update collectible click on it</h4>
                        <div style="background:white;color:black;border-radius:5px;width=100%;padding:5px;">
                            {% for collectible in current_scene.collectibles.all %}
                            <div>
                                {% if collectible.name %}
                                    <a href="#" style="width:100%">{{ collectible.name }}</a>
                                {% else %}
                                    <a href="#" style="width:100%">No Name</a>
                                {% endif %}
                            </div>
                            {% empty %}
                                None
                            {% endfor %}
                        </div>
                        <a class="btn btn-secondary" style="width:100%" href="{% url 'collectible' current_scene.id %}">Add new Collectible</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story/templates/story/game_over.html
{% extends "gapfiller/layout.html" %}
{% block body %}
    <h1>GameOver</h1>
{% endblock %}

story/templates/story/success.html
{% extends "gapfiller/layout.html" %}
{% block body %}
    <h1>Test</h1>
{% endblock %}

story/templates/story/sucess.html
{% extends "gapfiller/layout.html" %}
{% block body %}
    <h1>Test</h1>
{% endblock %}